---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: salada-db-pv-claim
  labels:
    app: salada-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: salada
spec:
  containers:
  - name: salada
    image: localhost:5000/salada:latest
    env:
    - name: POSTGRES_PASSWORD
      valueFrom:
        secretKeyRef:
          name: postgres-password-kube
          key: password
  - name: salada-db
    image: docker.io/library/postgres:latest
    volumeMounts:
    - name: postgres-persistent-storage
      mountPath: /var/lib/postgresql
  volumes:
  - name: postgres-persistent-storage
    persistentVolumeClaim:
      claimName: salada-db-pv-claim
